### ISSUE TITLE
(v4.0.2) iOS 8 EMMA_iOS: +[eMMa starteMMaSession:] crash

### ISSUE THREAD

**Issue by pmdevacc** [eMMaDevelopment/eMMa-iOS-SDK#1]
We recently pushed a new version of our app on which we have updated most of the used frameworks, and started receiving reports that the app would freeze on startup. Using Fabric's Crashlytics we  noticed that the below crash (stack trace) was affecting many users and narrowed down the occurrence to 100% of users using iOS8.
Is this something platform dependant? Is there a need to workaround for the app to bypass eMMa on iOS 8 or is it an issue that should be addressed?

Hope to get some feedback from you soon.
Best regards

`Crashed: com.apple.main-thread EXC_BREAKPOINT 0x00000001200d1088 Raw Text
0 libswiftUIKit.dylib	(Missing)
1	libswiftUIKit.dylib	(Missing)
2	libswiftUIKit.dylib	(Missing)
3	libdyld.dylib	dyld_stub_binder + 60
4	EMMA_iOS	-[AutoCoding setWithCoder:] + 348
5	EMMA_iOS	-[AutoCoding initWithCoder:] + 28
6	Foundation	_decodeObjectBinary + 2728
7	Foundation	_decodeObject + 304
8	Foundation	+[NSKeyedUnarchiver unarchiveObjectWithData:] + 104
9	EMMA_iOS	-[eMMaDataStoreController getObjectFromDataStore:] + 208
10	EMMA_iOS	-[eMMaSessionController init] + 108
11	EMMA_iOS	-[EMMAController initeMMa] + 220
12	libdispatch.dylib	_dispatch_client_callout + 16
13	libdispatch.dylib	dispatch_once_f + 96
14	EMMA_iOS	+[EMMAController sharedInstance] + 56
15    EMMA_iOS	+[eMMa starteMMaSession:] + 56
16    AppDelegate.m line 69 -[AppDelegate application:didFinishLaunchingWithOptions:]`

**Comment by jcornadoemma** [comment]
We're looking into it. Will update you soon

**Comment by adriancarrera31** [comment]
We have uploaded a new release (4.0.6) that it fixes the crash with iOS 8. We are waiting for your response to close the issue.

Thanks and regards.

**Comment by pmdevacc** [comment]
Hi there,
We have updated the sdk version and worked like a charm!
Thank you very much for your expedite response!

Best regards!
